version: "3.8"
services:
  cloudflared:
    image: cloudflare/cloudflared
    container_name: cloudflared-tunnel-service
    restart: unless-stopped
    networks:
      - cloudflared_tunnel_network
    command: tunnel run --token $CF_TOKEN
    environment:
      - CF_TOKEN=$CF_TOKEN
networks:
  cloudflared_tunnel_network:
    name: cloudflared_tunnel_network
