version: "3.8"
services:
  cloudflared:
    image: cloudflare/cloudflared
    container_name: cloudflared-service
    restart: unless-stopped
    networks:
      - cloudflared_tunnel_network
    secrets:
      - cloudflared_secret
    command: tunnel --credentials-file /run/secrets/cloudflared_secret run webmikas
secrets:
  cloudflared_secret:
    file: /docker/secrets/cloudflared
networks:
  cloudflared_tunnel_network:
    name: cloudflared_tunnel_network
