version: "3.8"
services:
  languagetool:
    image: erikvl87/languagetool:latest
    container_name: languagetool-service
    ports:
      - 8010:8010
    restart: unless-stopped
    volumes:
      - /docker/volumes/languagetool/ngrams:/ngrams
    environment:
      - langtool_languageModel=/ngrams
      - Java_Xms=512m
      - Java_Xmx=1g
    networks:
      - main_services

  webdav:
    image: derkades/webdav:latest
    container_name: webdav-service
    environment:
      - USERNAME=mikael
    restart: unless-stopped
    entrypoint:
      [
        "bash",
        "-c",
        "export PASSWORD=$$(cat /run/secrets/webdav_secret) ; source /entrypoint.sh",
      ]
    ports:
      - 8020:80
    volumes:
      - /docker/volumes/webdav/files:/data
    secrets:
      - webdav_secret
    networks:
      - main_services
secrets:
  webdav_secret:
    file: /docker/secrets/webdav
networks:
  main_services:
    name: main_services
