version: "3.8"
services:
  languagetool:
    image: erikvl87/languagetool:latest
    container_name: languagetool-service
    ports:
      - 8010:8010
    restart: unless-stopped
    volumes:
      - /docker/volumes/languagetool/ngrams:/ngrams
    environment:
      - langtool_languageModel=/ngrams
      - Java_Xms=512m
      - Java_Xmx=1g
    networks:
      - main_services

  webdav:
    image: derkades/webdav:latest
    container_name: webdav-service
    environment:
      - USERNAME=mikael
      - PASSWORD=${PASSWORD}
    restart: unless-stopped
    ports:
      - 8020:80
    volumes:
      - /docker/volumes/webdav/files:/data
    networks:
      - main_services

networks:
  main_services:
    name: main_services
