version: "3"

services:
  woodpecker-server:
    image: woodpeckerci/woodpecker-server:latest
    restart: unless-stopped
    container_name: woodpecker-server
    ports:
      - 8030:8000
      - 8031:9000
    volumes:
      - /docker/volumes/woodpecker-server-data:/var/lib/woodpecker/
    environment:
      - WOODPECKER_OPEN=true
      - WOODPECKER_HOST=https://woodpecker.webmikas.com
      - WOODPECKER_GITHUB=true
      - WOODPECKER_GITHUB_CLIENT=${WOODPECKER_GITHUB_CLIENT}
      - WOODPECKER_GITHUB_SECRET=${WOODPECKER_GITHUB_SECRET}
      - WOODPECKER_AGENT_SECRET=${WOODPECKER_AGENT_SECRET}
    networks:
      - woodpecker

  woodpecker-agent-arm:
    image: woodpeckerci/woodpecker-agent:latest
    container_name: woodpecker-agent-arm
    restart: unless-stopped
    depends_on:
      - woodpecker-server
    volumes:
      - /docker/volumes/woodpecker-agent-data:/etc/woodpecker
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WOODPECKER_SERVER=woodpecker-server:9000
      - WOODPECKER_AGENT_SECRET=${WOODPECKER_AGENT_SECRET}
    networks:
      - woodpecker

  woodpecker-agent-x86:
    image: woodpeckerci/woodpecker-agent:latest
    container_name: woodpecker-agent-x86
    restart: unless-stopped
    extra_hosts:
      - arm:10.0.0.196
    volumes:
      - /docker/volumes/woodpecker-agent-data:/etc/woodpecker
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WOODPECKER_SERVER=arm:8031
      - WOODPECKER_AGENT_SECRET=${WOODPECKER_AGENT_SECRET}
    networks:
      - woodpecker

networks:
  woodpecker:
    name: woodpecker
