version: '3'

services:
  woodpecker-server:
    image: woodpeckerci/woodpecker-server:latest
    container_name: woodpecker-server
    ports:
      - 8030:8000
      - 8031:9000
    entrypoint:
      - /bin/woodpecker-server
      - --server-host
      - https://woodpecker.webmikas.com
      - --github-secret
      - $(cat /run/secrets/woodpecker_github_secret)
      - --agent-secret
      - $(cat /run/secrets/woodpecker_agent_secret)
    volumes:
      - /docker/volumes/woodpecker-server-data:/var/lib/woodpecker/
    environment:
      - WOODPECKER_OPEN=true
      - WOODPECKER_GITHUB=true
      - WOODPECKER_GITHUB_CLIENT=f8cf40e5df67f2d08d4e
    secrets:
      - woodpecker_agent_secret
      - woodpecker_github_secret
    networks:
      - woodpecker

  woodpecker-agent:
    image: woodpeckerci/woodpecker-agent:latest
    container_name: woodpecker-agent
    entrypoint: 
      - /bin/woodpecker-agent
      - --server
      - woodpecker-server:9000
      - --grpc-token 
      - $(cat /run/secrets/woodpecker_agent_secret)
    restart: always
    depends_on:
      - woodpecker-server
    volumes:
      - /docker/volumes/woodpecker-agent-data:/etc/woodpecker
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - woodpecker_agent_secret
    networks:
      - woodpecker

secrets:
  woodpecker_agent_secret:
    file: /docker/secrets/woodpecker-agent-secret
  woodpecker_github_secret:
    file: /docker/secrets/woodpecker-github-secret

networks:
  woodpecker:
    name: woodpecker
