version: "3"
services:
  languagetool:
    image: erikvl87/languagetool
    container_name: languagetool
    ports:
        - 8010:8010
    environment:
        - langtool_languageModel=/ngrams
        - Java_Xms=512m
        - Java_Xmx=1g
    volumes:
        - ./volumes/ngrams:/ngrams
    restart: unless-stopped